{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 5}, "tests": {"0": {"status": "ERROR", "message": "request = <SubRequest 'init_driver' for <Function test_search_show[chrome]>>\n\n    @pytest.fixture(params=[\"chrome\"], scope=\"class\")\n    def init_driver(request):\n        if request.param == \"chrome\":\n>           web_driver = webdriver.Chrome(executable_path=TestData.CHROME_EXECUTABLE_PATH_MAC)\n\nTests/conftest.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nvenv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py:73: in __init__\n    self.service.start()\nvenv/lib/python3.9/site-packages/selenium/webdriver/common/service.py:98: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.chrome.service.Service object at 0x7f8f363dffa0>\n\n    def assert_process_still_running(self):\n        return_code = self.process.poll()\n        if return_code is not None:\n>           raise WebDriverException(\n                'Service %s unexpectedly exited. Status code was: %s'\n                % (self.path, return_code)\n            )\nE           selenium.common.exceptions.WebDriverException: Message: Service /Users/NHari/Desktop/chromedriver unexpectedly exited. Status code was: -9\n\nvenv/lib/python3.9/site-packages/selenium/webdriver/common/service.py:109: WebDriverException\n", "test_name": "test_search_show[chrome]", "rerun": "0"}, "1": {"status": "ERROR", "message": "request = <SubRequest 'init_driver' for <Function test_search_show[chrome]>>\n\n    @pytest.fixture(params=[\"chrome\"], scope=\"class\")\n    def init_driver(request):\n        if request.param == \"chrome\":\n>           web_driver = webdriver.Chrome(executable_path=TestData.CHROME_EXECUTABLE_PATH_MAC)\n\nTests/conftest.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nvenv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py:73: in __init__\n    self.service.start()\nvenv/lib/python3.9/site-packages/selenium/webdriver/common/service.py:98: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.chrome.service.Service object at 0x7f8f363dffa0>\n\n    def assert_process_still_running(self):\n        return_code = self.process.poll()\n        if return_code is not None:\n>           raise WebDriverException(\n                'Service %s unexpectedly exited. Status code was: %s'\n                % (self.path, return_code)\n            )\nE           selenium.common.exceptions.WebDriverException: Message: Service /Users/NHari/Desktop/chromedriver unexpectedly exited. Status code was: -9\n\nvenv/lib/python3.9/site-packages/selenium/webdriver/common/service.py:109: WebDriverException\n", "test_name": "test_remove_show[chrome]", "rerun": "0"}, "2": {"status": "ERROR", "message": "request = <SubRequest 'init_driver' for <Function test_search_show[chrome]>>\n\n    @pytest.fixture(params=[\"chrome\"], scope=\"class\")\n    def init_driver(request):\n        if request.param == \"chrome\":\n>           web_driver = webdriver.Chrome(executable_path=TestData.CHROME_EXECUTABLE_PATH_MAC)\n\nTests/conftest.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nvenv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py:73: in __init__\n    self.service.start()\nvenv/lib/python3.9/site-packages/selenium/webdriver/common/service.py:98: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.chrome.service.Service object at 0x7f8f363dffa0>\n\n    def assert_process_still_running(self):\n        return_code = self.process.poll()\n        if return_code is not None:\n>           raise WebDriverException(\n                'Service %s unexpectedly exited. Status code was: %s'\n                % (self.path, return_code)\n            )\nE           selenium.common.exceptions.WebDriverException: Message: Service /Users/NHari/Desktop/chromedriver unexpectedly exited. Status code was: -9\n\nvenv/lib/python3.9/site-packages/selenium/webdriver/common/service.py:109: WebDriverException\n", "test_name": "test_add_to_watchlist[chrome]", "rerun": "0"}, "3": {"status": "ERROR", "message": "request = <SubRequest 'init_driver' for <Function test_search_show[chrome]>>\n\n    @pytest.fixture(params=[\"chrome\"], scope=\"class\")\n    def init_driver(request):\n        if request.param == \"chrome\":\n>           web_driver = webdriver.Chrome(executable_path=TestData.CHROME_EXECUTABLE_PATH_MAC)\n\nTests/conftest.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nvenv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py:73: in __init__\n    self.service.start()\nvenv/lib/python3.9/site-packages/selenium/webdriver/common/service.py:98: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.chrome.service.Service object at 0x7f8f363dffa0>\n\n    def assert_process_still_running(self):\n        return_code = self.process.poll()\n        if return_code is not None:\n>           raise WebDriverException(\n                'Service %s unexpectedly exited. Status code was: %s'\n                % (self.path, return_code)\n            )\nE           selenium.common.exceptions.WebDriverException: Message: Service /Users/NHari/Desktop/chromedriver unexpectedly exited. Status code was: -9\n\nvenv/lib/python3.9/site-packages/selenium/webdriver/common/service.py:109: WebDriverException\n", "test_name": "test_all_sorts[chrome]", "rerun": "0"}, "4": {"status": "ERROR", "message": "request = <SubRequest 'init_driver' for <Function test_search_show[chrome]>>\n\n    @pytest.fixture(params=[\"chrome\"], scope=\"class\")\n    def init_driver(request):\n        if request.param == \"chrome\":\n>           web_driver = webdriver.Chrome(executable_path=TestData.CHROME_EXECUTABLE_PATH_MAC)\n\nTests/conftest.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nvenv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py:73: in __init__\n    self.service.start()\nvenv/lib/python3.9/site-packages/selenium/webdriver/common/service.py:98: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.chrome.service.Service object at 0x7f8f363dffa0>\n\n    def assert_process_still_running(self):\n        return_code = self.process.poll()\n        if return_code is not None:\n>           raise WebDriverException(\n                'Service %s unexpectedly exited. Status code was: %s'\n                % (self.path, return_code)\n            )\nE           selenium.common.exceptions.WebDriverException: Message: Service /Users/NHari/Desktop/chromedriver unexpectedly exited. Status code was: -9\n\nvenv/lib/python3.9/site-packages/selenium/webdriver/common/service.py:109: WebDriverException\n", "test_name": "test_refine_results[chrome]", "rerun": "0"}}, "suite_name": "Tests/test_UserHomePage.py"}}}, "date": "July 02, 2021", "start_time": 1625255807, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "5", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "5"}